#!/bin/bash
. "${HOME}/.cache/wal/colors.sh"

devices="$XDG_CONFIG_HOME/bluetooth_devices"

selected=$(awk -v pat=$(awk '{print $1}' $devices | dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -l 10 -p "connect to which device?") '$0~pat{print $2}' $devices)
bt_string=$(systemctl is-active bluetooth)

if [ $selected == "dc" ]; then
    [ $bt_string == "active" ] && echo -e "power off\n" | bluetoothctl
elif [ $selected == "sw" ]; then
    toggle_bluetooth
else
    [ $bt_string == "inactive" ] && sudo -A systemctl start bluetooth &
    wait
    echo -e "power on\n" | bluetoothctl
    sleep 0.15
    echo -e "connect $selected\n" | bluetoothctl
    sleep 2
    IFS=$'\n'
    info=($(echo -e "info $selected\n" | bluetoothctl | awk -F ':' '/(Connected:|Name:)/ {print $2}'))
    unset IFS
    if [ ${info[1]} == "yes" ]; then
        pgrep -x dunst >/dev/null && notify-send "<b>${info[0]}</b> connected"
    else
        pgrep -x dunst >/dev/null && notify-send "failed to connect <b>${info[0]}</b>"
    fi
fi
