#!/bin/sh

prepend=". \"\${HOME}/.cache/wal/colors.sh\""
for FILE1 in "$@"
do
    if grep -q dmenu $FILE1; then
        if grep -q '$prepend' $FILE1; then
            echo $prepend|cat - $FILE1 > /tmp/out && mv /tmp/out $FILE1
        fi
        sed -i 's/-\(nb\|nf\|sb\|sf\) [^ ]*//g' $FILE1
        sed -i 's/dmenu/dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"/g' $FILE1
    fi
done
