#!/bin/bash

audio_device="pulse/alsa_output.pci-0000_00_1b.0.analog-stereo"
mpv --really-quiet --volume=130 --audio-device="$audio_device" "$XDG_DATA_HOME"/sounds/notification/notify.opus
mpv --really-quiet "$XDG_DATA_HOME"/sounds/notification/notify.opus
