#!/bin/bash

status=$(cat /sys/class/power_supply/BAT1/status)

if [ "$status" == "Charging" ]; then
    pgrep -x dunst &>/dev/null &&
    notify-send -t 5000 -u critical "Battery is charging! Please unplug the power adapter before shutdown!" &&
    mynotify
    exit
fi

sudo shutdown -h now
