#!/bin/bash

dmenu_color(){
    dmenu_colored -i -l 10 -p "$1"
}

new="generate new password"
delete="delete secret"
change="change length and don't use symbols"
chosen=$(printf "$(gopass ls -f)\n$new\n$delete\n$change" | dmenu_color "Which secret?" | awk '{print $1}')
[ -z $chosen ] && exit
if [ "$chosen" == "generate" ]; then
    folder=$(printf "$(gopass ls --fo)" | dmenu_color "Which folder?" | awk '{print $1}')
    [ -z $folder ] && exit
    name=$(</dev/null dmenu_color "Which name?" | awk '{print $1}')
    [ -z $name ] && exit
    gopass --yes generate -s $folder/$name 24 && notify-send "New password in $folder/$name copied to clipboard."
    exit
elif [ "$chosen" == "delete" ]; then
    rm_file=$(printf "$(gopass ls -f)" | dmenu_color "Which secret?" | awk '{print $1}')
    [ -z $rm_file ] && exit
    gopass --yes rm $rm_file && notify-send "$rm_file deleted!"
    exit
elif [ "$chosen" == "change" ]; then
    change_file=$(printf "$(gopass ls -f)" | dmenu_color "Which secret?" | awk '{print $1}')
    [ -z $change_file ] && exit
    length=$(</dev/null dmenu_color "Which length?" | awk '{print $1}')
    [ -z $length ] && exit
    re='^[0-9]+$'
    if ! [[ $length =~ $re ]] ; then
        notify-send "ERROR: Length must be a number!" && exit 1
    fi
    gopass --yes generate $change_file $length && notify-send "New password with length <b>$length</b> copied to clipboard."
    exit
fi
secret=$(gopass show $chosen)
[ -z $secret ] && exit
echo $secret | xclip -selection c

id=$(xdotool getactivewindow)
if [ $(xprop -id $id | grep -Eic "(firefox|chromium)") -eq 0 ]; then
    modifier="alt"
else
    modifier="ctrl"
fi

xdotool key --window "$id" "$modifier+v"

notify-send "Secret in $chosen copied to clipboard.
Will clear in 6 seconds."
sleep 6
echo "" | xclip -selection c
notify-send "Clipboard cleared!"
