#!/bin/bash

. "${HOME}/.cache/wal/colors.sh"

dmenu_color(){
    dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -i -l 10 -p "$1"
}

new="generate new password"
delete="delete secret"
chosen=$(printf "$(gopass ls -f)\n$new\n$delete" | dmenu_color "Which secret?" | awk '{print $1}')
[ -z $chosen ] && exit
if [ "$chosen" == "generate" ]; then
    folder=$(printf "$(gopass ls --fo)" | dmenu_color "Which folder?" | awk '{print $1}')
    [ -z $folder ] && exit
    name=$(</dev/null dmenu_color "Which name?" | awk '{print $1}')
    [ -z $name ] && exit
    gopass --yes generate -s $folder/$name 24 && notify-send "New password copied to clipboard."
    exit
elif [ "$chosen" == "delete" ]; then
    rm_file=$(printf "$(gopass ls -f)" | dmenu_color "Which secret?" | awk '{print $1}')
    [ -z $rm_file ] && exit
    gopass --yes rm $rm_file && notify-send "$rm_file deleted!"
    exit
fi
secret=$(gopass show $chosen)
[ -z $secret ] && exit
echo $secret | xclip -selection c
notify-send "Secret copied to clipboard.
Will clear in 6 seconds."
sleep 6
echo "" | xclip -selection c
notify-send "Clipboard cleared!"
