#!/bin/bash

. "${HOME}/.cache/wal/colors.sh"
chosen=$(echo "$(gopass ls -f)" | dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -i -l 10 -p "Which password?" | awk '{print $1}')
[ -z $chosen ] && exit
gopass show $chosen | xclip -selection c
notify-send "Secret copied to clipboard.
Will clear in 6 seconds."
sleep 6
echo "" | xclip -selection c
notify-send "Clipboard cleared!"
