#!/bin/bash
alias mkd="mkdir -pv" \
    mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
    SS="sudo -A systemctl" \
    r="$FILE" \
    g="./gradlew" \
    e="nvim_mru" \
    v="$EDITOR" \
    x="sxiv -ft *" \
    ls="ls -hN --color=auto --group-directories-first" \
    s="sudo -A" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ffmpeg="ffmpeg -hide_banner" \
    ga="git add -u" \
    gst="git status" \
    smi="sudo -A make -k clean install" \
    car="source /opt/anaconda3/bin/activate root" \
    q="exit" \
    vim="nvim" \
    vimdiff="nvim -d" \
    nvm="unalias nvm && source $NVM_DIR/nvm.sh --no-use && nvm"

gitdir() {
    svn --config-dir $XDG_CONFIG_HOME/subversion checkout ${1%.git}'/trunk/'$2 $HOME'/Downloads/'$(echo ${2%/} | awk -F '/' '{print $NF}')
}

gitignore() {
    echo -e "add following files to gitignore:\n"
    git status 2>/dev/null | grep -P '\t' | grep -v '.*: ' | tr -d '\t' | sed 's/\ /\\\ /g' | tee -a .git/info/exclude
}

gpt() {
    if ! type "git_prompt_toggle" >/dev/null 2>&1; then
        GIT_PROMPT_THEME=Solarized_Extravagant
        source $XDG_DATA_HOME/bash-git-prompt/gitprompt.sh
        GIT_PROMPT_ONLY_IN_REPO=1
        git status
        return
    fi
    git_prompt_toggle
    git status
}
