#!/bin/bash
alias mkd="mkdir -pv" \
    mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
    p="sudo pacman" \
    SS="sudo -A systemctl" \
    r="launch_lf" \
    g="./gradlew" \
    e="nvim_mru" \
    v="$EDITOR" \
    x="sxiv -ft *" \
    ls="ls -hN --color=auto --group-directories-first" \
    ll="ls -hNal --color=auto --group-directories-first" \
    s="sudo -A" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ffmpeg="ffmpeg -hide_banner" \
    ga="git add -u" \
    gst="git status" \
    gc="gitmyclone" \
    gl="git log --stat --pretty=short --graph" \
    gb="git branch -r --no-merged | sed 's/origin\///'" \
    gbd="git branch | egrep -v '(master|\*)' | xargs git branch -D" \
    smi="sudo -A make -k clean install && sudo -A make -k clean" \
    car="source /opt/anaconda3/bin/activate root" \
    q="exit" \
    vim="nvim" \
    vimdiff="nvim -d" \
    nvm="unalias nvm && source_nvm && nvm" \
    npm="unalias npm && nvm use default && npm"

gitdir() {
    svn --config-dir $XDG_CONFIG_HOME/subversion checkout ${1%.git}'/trunk/'$2 $HOME'/Downloads/'$(echo ${2%/} | awk -F '/' '{print $NF}')
}

gitignore() {
    old_dir=$(pwd)
    working_dir=$(pwd)

    while [ ! -d $working_dir/.git ]
    do
        [ $working_dir == "/" ] && echo "no git repo found!" && return
        cd ..
        working_dir=$(pwd)
    done
    echo "git repo found in $working_dir"

    echo -e "add following files to gitignore:\n"
    git status 2>/dev/null | grep -P '\t' | grep -v '.*: ' | tr -d '\t' | sed 's/\ /\\\ /g' | tee -a "$working_dir"/.git/info/exclude

    cd "$old_dir"
}

source_nvm() {
    source /usr/share/nvm/nvm.sh --no-use
}

gitmyclone() {
    repo="$1"
    shift
    git clone git@github.com:otlin100/"$repo" "$@"
}

mywoof() {
    location="$1"
    url=http://192.168.178.50:8080
    shift
    curl $url/"$location"
}

gpt() {
    if ! type "git_prompt_toggle" >/dev/null 2>&1; then
        GIT_PROMPT_THEME=Solarized_Extravagant
        source /usr/lib/bash-git-prompt/gitprompt.sh
        GIT_PROMPT_ONLY_IN_REPO=1
        git status
        return
    fi
    git_prompt_toggle
    git status
}
