#!/bin/bash

cache="$XDG_CACHE_HOME/via"

expand_tilda() {
    for x in $(cat -); do
        echo "${x/#\~/$HOME}"
    done
}

if [[ "$1" == "-r" ]] || [[ ! -e "$cache" ]]; then
	cat "$XDG_CONFIG_HOME/via/shortcuts" > "$cache" 2>/dev/null
	cat "$XDG_CONFIG_HOME/via/websites" >> "$cache"
	cat "$XDG_CONFIG_HOME/shortcuts/bmdirs" | cut -f2 | expand_tilda >> "$cache"
	cat "$XDG_CONFIG_HOME/shortcuts/bmfiles" | cut -f2 | expand_tilda >> "$cache"
	find "$HOME" -mindepth 1 \( -name ".*" -o -path "$HOME/code/*" \) -prune -o -print | sort >> "$cache"
    dmenu_path >> "$cache"
fi

cat "$cache"
