#!/bin/bash

exec &> /dev/null

while read arg; do
	# first try matching by filename or pathname
	case "${arg,,}" in
		http*)
			$BROWSER "$arg" &
			;;
		# [^/]*) # doesn't start with '/'
		# 	sh -c "$arg"
		# 	;;
		*.txt)
			$TERMINAL $EDITOR "$arg" &
			;;
		*.pdf | *.epub)
			$READER "$arg" &
			;;
		*.mp3)
			$TERMINAL mpv "$arg" &
			;;
		*.od[tsp]|*.doc|*.docx|*.ppt|*.pptx|*.xls|*.xlsx)
			libreoffice "$arg" &
			;;
		*)
			# then try matching by mimetype
			mimetype=$(file -Lb --mime-type "$arg")
			case "$mimetype" in
				text/html)
					$BROWSER "$arg" &
					;;
				text/* | inode/x-empty | message/rfc822)
					$TERMINAL $EDITOR "$arg" &
					;;
				inode/directory)
                    $TERMINAL $FILE "$arg" &
					;;
				image/*)
					sxiv "$arg" &
					;;
				*)
					exit 1
					;;
			esac
			;;
	esac
done
