#!/bin/sh

setxkbmap -option caps:super && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
xmodmap -e 'keycode 105 = Caps_Lock' &
xmodmap -e 'keycode 135 = Super_R' &
wal -n -R

eval $(hub alias -s)

sxhkd -m 1 &	# Bind keys
xset r rate 190 48 &
unclutter &		# Remove mouse when idle
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
mpdupdate &

xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"
redshift -P -O 5000

gpgconf --homedir /home/otlin/.config/gnupg --launch gpg-agent
autorandr -c

exec i3
