#!/bin/sh

setbg &
wal -n -R

eval $(ssh-agent -s)
eval $(hub alias -s)

sxhkd -m 1 &	# Bind keys
setxkbmap -option caps:super && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
xmodmap -e 'keycode 105 = Caps_Lock' &
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 200 50 &
unclutter &		# Remove mouse when idle
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
mpdupdate &

xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"
redshift -P -O 5000
source "$XDG_CONFIG_HOME/screenlayout/default.sh"
gpg-agent --homedir /home/otlin/.config/gnupg --daemon

exec i3
