#!/bin/sh

wal -R

# [ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
[ -f "$XDG_CONFIG_HOME/X11/Xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"

redshift -P -O 5000

xset r rate 200 50

exec i3
