#!/bin/bash
alias mkd="mkdir -pv" \
    mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
    p="sudo pacman" \
    SS="sudo systemctl" \
    r="$FILE" \
    g="git" \
    e="$EDITOR" \
    v="$EDITOR" \
    x="sxiv -ft *" \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ffmpeg="ffmpeg -hide_banner" \
    gpom="git push origin master" \
    gpo="git pull origin" \
    ga="git add -u" \
    gc="git commit -m" \
    gst="git status" \
    smi="sudo -A make -k clean install" \
    car="source /opt/anaconda3/bin/activate root" \
    q="exit" \
    vim="nvim" \
    vimdiff="nvim -d" \
    nvm="unalias nvm && source /usr/share/nvm/nvm.sh --no-use && nvm"

vf() { fzf | xargs -r -I % $EDITOR % ;}

gitdir() {
    svn --config-dir $XDG_CONFIG_HOME/subversion checkout ${1%.git}'/trunk/'$2 $HOME'/Downloads/'$(echo ${2%/} | awk -F '/' '{print $NF}')
}

gitignore() {
    git status|grep -P '\t'|awk '{print $1}' >> .git/info/exclude;
}

gpt() {
    if ! type "git_prompt_toggle" >/dev/null 2>&1; then
        source $XDG_DATA_HOME/bash-git-prompt/gitprompt.sh
        GIT_PROMPT_ONLY_IN_REPO=1
        git status
        [ $(ssh-add -l | grep -c otto.lin@hhu.de) -eq 1 ] || echo none | ssh-add ~/.ssh/id_rsa
        return
    fi
    git_prompt_toggle
    git status
}
