#!/bin/sh
. "${HOME}/.cache/wal/colors.sh"
# dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -fn Monospace-18 -p "$1" <&- && echo
dmenu -nb "#000000" -nf "#000000" -sb "$color1" -sf "$color15" -p "$1" <&-
