#!/bin/sh
# Feed this script a link and it will give dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"
# some choice programs to use to open it.

. "${HOME}/.cache/wal/colors.sh"

case "$(printf "copy url\\nmpv\\nmpv (loop)\\nqueue download\\n\\nqueue youtube-dl\\nfeh\\nbrowser\\nw3m\\nmpv (float)" | dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -i -p "Open link with what program?")" in
    "copy url") echo "$1" | xclip -selection clipboard ;;
    mpv) setsid mpv -quiet "$1" >/dev/null 2>&1 & ;;
    "mpv (loop)") setsid mpv -quiet --loop "$1" >/dev/null 2>&1 & ;;
    "queue download") tsp curl -LO "$1" >/dev/null 2>&1 ;;
    "queue youtube-dl") tsp youtube-dl --write-metadata -ic "$1" >/dev/null 2>&1 ;;
    browser) setsid "$BROWSER" "$1" >/dev/null 2>&1 & ;;
    feh) setsid feh "$1" >/dev/null 2>&1 & ;;
    w3m) w3m "$1" >/dev/null 2>&1 ;;
    "mpv (float)") setsid mpv --geometry=+0-0 --autofit=30%  --title="mpvfloat" "$1" >/dev/null 2>&1 & ;;
esac
