#!/bin/sh

# case $BLOCK_BUTTON in
#     1) setsid "$TERMINAL" -e toggle_bluetooth ;;
# esac

bt_string=$(systemctl is-active bluetooth)

if [[ $bt_string == 'active' ]]; then
    printf "%s\\n" ""
else
    printf ""
fi
