#!/bin/sh

# Gives a dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# Anything else, it search it.
. "${HOME}/.cache/wal/colors.sh"

pgrep -x dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" && exit

choice=$(echo "🦆" | dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -i -p "Search DuckDuckGo:") || exit 1

if [ "$choice" = "🦆"  ]; then
	$BROWSER "https://duckduckgo.com"
else
	$BROWSER "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
fi
