#!/bin/sh
# A dmenu_colored binary prompt script.
# Gives a dmenu_colored prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "No\\nYes" | dmenu_colored -i -p "$1" = "Yes" ] && $2
